// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmuumegUSpZ-Tfp9h2lO3q8mIyy8LjWw',
    appId: '1:499874925233:web:b0b7b4bb8359add123f090',
    messagingSenderId: '499874925233',
    projectId: 'plantly-37af9',
    authDomain: 'plantly-37af9.firebaseapp.com',
    storageBucket: 'plantly-37af9.appspot.com',
    measurementId: 'G-TW3PPE6391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQY8ndWErMlkKy3Jj3GR4gKA4Pfb7K2s',
    appId: '1:499874925233:android:43d41f4d147082ea23f090',
    messagingSenderId: '499874925233',
    projectId: 'plantly-37af9',
    storageBucket: 'plantly-37af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pKnvyFpv4G3_Rs8Pps35TZQLr5f2HdI',
    appId: '1:499874925233:ios:eb5f3625bc40bb0223f090',
    messagingSenderId: '499874925233',
    projectId: 'plantly-37af9',
    storageBucket: 'plantly-37af9.appspot.com',
    iosClientId: '499874925233-26g3p0fnvieuirb2btfc4ml3fjhhbka2.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantly',
  );
}
